# VMWare Alpine Docker config
Vagrant.configure("2") do |config|

    config.vm.box = "generic/alpine312"
    config.vm.define "Alpine DOcker"
    config.vm.hostname ="alpvm"
    config.vm.provider "vmware_desktop" do |v|
      v.gui = true
      v.vmx["memsize"] = "4096"
      v.vmx["numvcpus"] = "4"
    end
  
    config.vm.provision "shell", inline: <<-SHELL
      echo "http://nl.alpinelinux.org/alpine/v3.12/main" >  /etc/apk/repositories
      echo "http://nl.alpinelinux.org/alpine/v3.12/community" >  /etc/apk/repositories
      apk update
      apk add docker
      addgroup $USER docker
      rc-update add docker boot
      service docker start
      # Adding Docker Compose
      apk add py-pip python3-dev libffi-dev openssl-dev gcc libc-dev make
      pip3 install docker-compose
      reboot now
    SHELL
  end
  